apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
    name: sif-innsyn
    namespace: dusseldorf
    labels:
        team: dusseldorf
spec:
    image: {{ image }}
    port: 8080
    liveness:
        path: /familie/sykdom-i-familien/soknad/innsyn/health/isAlive
        initialDelay: 20
        timeout: 1
        periodSeconds: 5
        failureThreshold: 10
    readiness:
        path: /familie/sykdom-i-familien/soknad/innsyn/health/isReady
        initialDelay: 20
        timeout: 1
    resources:
        limits:
            cpu: 2000m
            memory: 512Mi
        requests:
            cpu: 50m
            memory: 128Mi
    ingresses:
        - https://sif-innsyn.labs.nais.io
    replicas:
        min: 1
        max: 1
        cpuThresholdPercentage: 90
    prometheus:
        enabled: true
        path: /metrics
    vault:
        enabled: false
    env:
        - name: APPRES_CMS_URL
          value: https://appres.nav.no
        - name: API_URL
          value: https://sif-innsyn-api.labs.nais.io
        - name: PUBLIC_PATH
          value: /familie/sykdom-i-familien/soknad/innsyn
        - name: LOGIN_URL
          value: https://loginservice.dev.nav.no/login?redirect=https://sif-innsyn.dev.nav.no/familie/sykdom-i-familien/soknad/innsyn
        - name: UTILGJENGELIG
          value: "off"
        - name: MELLOMLAGRING
          value: "on"
